Update Content.js
krasimir/githorn-playground pull request #16
Opened 2019-05-04 03:47 UTC by stefantsonev2019

2019-05-04 03:50 UTC, krasimir commented on Content.js
> +  const something = 42;
You sure?

2019-05-04 03:50 UTC, krasimir requested changes

2019-05-04 03:50 UTC, krasimir commented on Content.js
> +    submit(true);
I'm not sure about that. Maybe should be still `false` ❔

2019-05-04 03:50 UTC, krasimir commented on Header.js
> +      <p>Hello</p>
Can we come with better copy here.

2019-05-04 03:51 UTC, stefantsonev2019 commented on Content.js
> +  const something = 42;
Not really.

2019-05-04 03:51 UTC, stefantsonev2019 commented on Header.js
> +      <p>Hello</p>
Ok, I'll think about it.

2019-05-04 04:08 UTC, krasimir commented on Content.js
> -        <img src={ profile.avatar } className='avatar bold' title={ profile.login }/>
Why is this removed?

2019-05-04 04:35 UTC, stefantsonev2019 commented on Content.js
> +  const something = 42;
That's just testing.

2019-05-04 04:36 UTC, krasimir commented on Content.js
> +/* A Comment here. */
Shall we go with:
```
// A Comment here
```

2019-05-08 14:25 UTC, krasimir commented on Content.js
>        { (isEditing && !submitted) && <div className='left mt05 ml2'>
One More comment.

2019-10-06 04:22 UTC, krasimir commented on Content.js
> +/* A Comment here. */
Riew works

2019-10-06 04:23 UTC, krasimir commented on Content.js
>    const [ deleteSure, areYouSure ] = useState(false);
A new comment but I can't see the delete and edit button.

2019-10-06 04:25 UTC, krasimir commented on Content.js
> +/* A Comment here. */
nnn

2019-10-18 16:02 UTC, merged