Create README.md
krasimir/githorn-playground pull request #2
Opened 2019-03-16 07:48 UTC by stefantsonev2019

I think we need a README file.

2019-03-16 07:49 UTC, stefantsonev2019 commented
As an addition to the changes in #1

2019-03-16 07:49 UTC, krasimir commented
Yep. I agree we should add a README file.

2019-03-16 07:50 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
Shall we add more description here?

2019-03-23 04:00 UTC, krasimir commented
Overall it looks good.

2019-03-23 06:57 UTC, stefantsonev2019 commented on README.md
> +A repo for testing while developing GitHorn
Yep. I'll do.

2019-03-23 06:57 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
Ok, thanks.

2019-03-23 07:05 UTC, krasimir commented
That's a new comment here.

2019-03-23 15:38 UTC, krasimir commented
AAA

2019-03-23 15:49 UTC, krasimir commented
A new one

2019-03-23 15:49 UTC, krasimir commented
OKL

2019-03-23 15:50 UTC, krasimir commented
GHH

2019-03-23 15:54 UTC, krasimir commented
hjsa22

2019-03-23 15:54 UTC, krasimir commented
33

2019-03-23 15:57 UTC, krasimir commented
oi

2019-03-23 15:58 UTC, krasimir commented
psps

2019-03-23 15:59 UTC, krasimir commented
gtr

2019-03-23 16:34 UTC, krasimir commented on README.md
> +# GitHorn playground
A thread

2019-03-23 16:34 UTC, krasimir commented on README.md
> +# GitHorn playground
With a comment.

2019-03-23 16:35 UTC, stefantsonev2019 commented on README.md
> +# GitHorn playground
A-ha

2019-03-23 16:37 UTC, krasimir commented on README.md
> +# GitHorn playground
Again

2019-03-23 16:38 UTC, stefantsonev2019 commented on README.md
> +# GitHorn playground
ddd

2019-03-23 16:38 UTC, krasimir commented on README.md
> +# GitHorn playground
u7u7

2019-03-23 16:41 UTC, krasimir commented on README.md
> +# GitHorn playground
1

2019-03-23 16:41 UTC, stefantsonev2019 commented on README.md
> +# GitHorn playground
2

2019-03-24 05:54 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
something to delete

2019-03-24 05:55 UTC, krasimir commented on README.md
> +# GitHorn playground
KKK

2019-03-24 05:55 UTC, stefantsonev2019 commented on README.md
> +# GitHorn playground
1

2019-03-24 05:55 UTC, krasimir commented on README.md
> +# GitHorn playground
ddd

2019-03-24 05:57 UTC, krasimir commented on README.md
> +# GitHorn playground
JJJ

2019-03-24 05:57 UTC, stefantsonev2019 commented on README.md
> +# GitHorn playground
ggg

2019-03-24 05:57 UTC, krasimir commented on README.md
> +# GitHorn playground
ttt

2019-03-24 05:58 UTC, krasimir commented on README.md
> +# GitHorn playground
1

2019-03-24 06:04 UTC, krasimir commented on README.md
> +# GitHorn playground
1

2019-03-24 06:04 UTC, krasimir commented on README.md
> +# GitHorn playground
2

2019-03-24 06:04 UTC, krasimir commented on README.md
> +# GitHorn playground
3

2019-03-24 15:51 UTC, krasimir commented on README.md
> +# GitHorn playground
now

2019-03-24 16:00 UTC, krasimir commented on README.md
> +# GitHorn playground
2223

2019-03-24 16:36 UTC, krasimir commented on README.md
> +# GitHorn playground
new comment

2019-03-24 16:38 UTC, krasimir commented on README.md
> +# GitHorn playground
kki

2019-03-24 16:48 UTC, krasimir commented on README.md
> +# GitHorn playground
Hello

2019-03-24 16:49 UTC, krasimir commented on README.md
> +# GitHorn playground
New one

2019-03-24 16:50 UTC, krasimir commented on README.md
> +# GitHorn playground
6555

2019-03-24 16:50 UTC, krasimir commented on README.md
> +# GitHorn playground
888

2019-03-25 03:56 UTC, krasimir commented on README.md
> +# GitHorn playground
Mon

2019-03-25 03:59 UTC, krasimir commented on README.md
> +# GitHorn playground
Thu

2019-03-27 04:19 UTC, krasimir commented
A single comment.

2019-03-27 04:22 UTC, krasimir approved these changes
Looks good.

2019-03-27 04:22 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
To review

2019-03-27 04:22 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
And it works yes.

2019-03-27 04:24 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
A new review has been started.

2019-03-27 04:52 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
A single comment.

2019-03-27 04:54 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
One more!

2019-03-28 04:15 UTC, stefantsonev2019 commented on README.md
> +A repo for testing while developing GitHorn
Do  you think that we ...

2019-03-28 04:37 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
Yes.

2019-03-28 04:38 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
And one more here.

2019-03-28 04:39 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
YYY

2019-03-28 04:40 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
TTT

2019-03-28 04:48 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
I think so.

2019-03-28 04:49 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
and 8888

2019-03-28 05:23 UTC, krasimir commented on README.md
> +# GitHorn playground
Ok let's see

2019-03-28 05:26 UTC, krasimir commented on README.md
> +# GitHorn playground
Hell

2019-03-28 05:31 UTC, krasimir commented on README.md
> +# GitHorn playground
ggh

2019-03-28 05:32 UTC, krasimir commented on README.md
> +
OK

2019-03-28 05:33 UTC, krasimir commented on README.md
> +
Empty

2019-03-28 05:34 UTC, krasimir commented on README.md
> +
YYYYY

2019-03-28 05:37 UTC, krasimir commented on README.md
> +
Yep

2019-03-28 05:42 UTC, krasimir commented on README.md
> +
Now this should work.

2019-03-28 05:46 UTC, krasimir commented on README.md
> +
Oh nice

2019-03-28 05:47 UTC, stefantsonev2019 commented on README.md
> +A repo for testing while developing GitHorn
uuu

2019-03-28 05:47 UTC, stefantsonev2019 commented on README.md
> +
yuyu

2019-03-28 06:09 UTC, krasimir approved these changes

2019-03-28 07:01 UTC, krasimir requested changes
no no asdsda
```
Hello
```

2019-03-28 07:01 UTC, krasimir commented on README.md
> +
ddd

2019-03-28 07:05 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
a new one

2019-03-28 07:05 UTC, krasimir approved these changes
Hm ... yes it may work indeed

2019-03-28 07:05 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
joker

2019-03-28 07:06 UTC, krasimir requested changes
I think that it is fine

2019-03-28 07:06 UTC, krasimir commented on README.md
> +A repo for testing while developing GitHorn
one m

2019-03-28 07:29 UTC, krasimir commented on README.md
> +
9090909090

2019-03-28 07:44 UTC, krasimir reviewed
nono34

2019-03-28 07:44 UTC, krasimir commented on README.md
> +
dsa

2019-03-28 08:10 UTC, krasimir approved these changes
Good work!

2019-03-28 08:13 UTC, krasimir requested changes
nope11

2019-03-28 08:14 UTC, krasimir reviewed
I have a few comments.

2019-03-29 16:13 UTC, closed without merging