Update Content.js
krasimir/githorn-playground pull request #3
Opened 2019-03-30 03:50 UTC by stefantsonev2019

A PR description here.

2019-03-30 03:53 UTC, krasimir commented on Content.js
>        </div> }
I like it.

2019-03-30 03:58 UTC, krasimir commented on Content.js
> +          <button className='brand cta' onClick={ () => comment('startReview') }>Start review</button>
One more.

2019-03-30 04:01 UTC, krasimir approved these changes

2019-03-30 04:01 UTC, krasimir commented on Content.js
> -          <button className='brand cta' onClick={ () => comment('startReview') }>Start review</button> }
You sure we have to delete it?

2019-03-30 04:01 UTC, krasimir commented on Root.js
>      </div>
Good one.

2019-03-30 04:19 UTC, krasimir commented on Content.js
>  */
C1

2019-03-30 04:19 UTC, krasimir commented on Content.js
> +          <button className='brand cta' onClick={ () => comment('startReview') }>Start review</button>
C2

2019-03-30 04:20 UTC, krasimir commented on Content.js
> +Comment here.
c1

2019-03-30 04:20 UTC, krasimir commented on Content.js
> +          <button className='brand cta' onClick={ () => comment('startReview') }>Start review</button>
c2

2019-03-30 04:23 UTC, krasimir commented on Content.js
>  */
test

2019-03-30 04:24 UTC, krasimir commented on Content.js
> +Comment here.
aaa

2019-03-30 04:24 UTC, krasimir commented on Content.js
> -          <button className='brand cta' onClick={ () => comment('startReview') }>Start review</button> }
ddd

2019-03-30 04:25 UTC, krasimir commented on Content.js
> +Comment here.
yu

2019-03-30 04:25 UTC, krasimir commented on Content.js
> +          <button className='brand cta' onClick={ () => comment('startReview') }>Start review</button>
uuu

2019-03-30 04:46 UTC, krasimir requested changes
I think that it is cool.

2019-03-30 04:46 UTC, krasimir commented on Content.js
> +Comment here.
C1

2019-03-30 04:46 UTC, krasimir commented on Root.js
> +      <Header>Hey, there!</Header>
C2

2019-03-30 04:49 UTC, krasimir commented on Root.js
>  function App() {
Nice

2019-03-30 04:49 UTC, krasimir commented on Root.js
>  function App() {
Second.

2019-03-30 04:51 UTC, krasimir approved these changes
I'm happy

2019-03-30 04:51 UTC, krasimir commented on Content.js
> -comment here
TUTUT

2019-03-30 06:25 UTC, krasimir approved these changes

2019-03-30 06:25 UTC, krasimir commented on Root.js
> +      <Header>Hey, there!</Header>
OOO

2019-03-30 06:25 UTC, krasimir commented on Root.js
> +      <Header>Hey, there!</Header>
444

2019-03-30 14:13 UTC, krasimir requested changes
more!

2019-03-30 14:13 UTC, krasimir commented on Root.js
> -      <Header>Hello world</Header>
Why?

2019-03-30 14:13 UTC, krasimir commented on Root.js
> +      <Header>Hey, there!</Header>
That's indeed a good suggestion!

2019-03-31 06:10 UTC, krasimir reviewed
A new one.

2019-03-31 06:11 UTC, krasimir commented
Just a comment.

2019-03-31 07:52 UTC, stefantsonev2019 commented on Root.js
> +      <Header>Hey, there!</Header>
One more from another user.

2019-03-31 13:24 UTC, krasimir commented
ONLYYYY

2019-03-31 13:25 UTC, krasimir commented on Root.js
> -      <Header>Hello world</Header>
hhhh

2019-03-31 13:26 UTC, krasimir reviewed
blah

2019-03-31 13:26 UTC, krasimir commented on Root.js
> -      <Header>Hello world</Header>
tyr

2019-03-31 13:28 UTC, krasimir approved these changes

2019-03-31 13:30 UTC, krasimir commented
null

2019-03-31 13:31 UTC, krasimir approved these changes

2019-03-31 13:40 UTC, stefantsonev2019 commented on Content.js
>  /* A
What you think!!!!!!!?

2019-03-31 15:36 UTC, krasimir commented
909010

2019-03-31 15:38 UTC, krasimir commented
1001

2019-03-31 15:39 UTC, krasimir commented
1002

2019-03-31 15:39 UTC, krasimir commented
Looks good, I'm thinking that this could be merged.

2019-04-02 08:45 UTC, krasimir commented
I would vote for this notation. So instead of `setContact` I would prefer `withContact`. I like the sequence of `withSomething().withSomething().build()`. It kinda speaks "create my thing with this and that". While `setSomething().setSomething().build()` tells "I have something created and I'm setting this and that and at the end ... oh wait I'm building it now".

2019-04-12 03:55 UTC, krasimir commented on Content.js
>  /* A
I think it is nice.

2019-04-12 11:42 UTC, krasimir commented
200

2019-04-12 12:04 UTC, krasimir commented
Go go

2019-04-12 12:08 UTC, krasimir commented
KKOL

2019-04-12 12:17 UTC, stefantsonev2019 commented on Content.js
> -          <button className='brand cta' onClick={ () => comment('startReview') }>Start review</button> }
Good one.

2019-04-12 12:18 UTC, krasimir commented on Content.js
> -          <button className='brand cta' onClick={ () => comment('startReview') }>Start review</button> }
Y

2019-04-12 12:18 UTC, stefantsonev2019 commented on Content.js
> -          <button className='brand cta' onClick={ () => comment('startReview') }>Start review</button> }
Y3

2019-04-12 14:06 UTC, krasimir commented
That's a good feedback imo.

2019-04-14 09:11 UTC, merged